FROM ubuntu:24.04

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-dev \
    libssl-dev \
    libffi-dev \
    python3-setuptools \
    build-essential \
    python3 \
    python3-pip \
    python3-venv \
    cmake \
    pkg-config \
    mingw-w64 \
    && apt-get clean
