name: R-Type

on: [push, pull_request]

env:
  MIRROR_URL: "git@github.com:EpitechPromo2027/B-CPP-500-LIL-5-2-rtype-leo.dumont.git"

jobs:
  push_to_mirror:
    name: Push to mirror
    if: ${{ github.ref_name == 'main' && github.event_name == 'push' }}
    runs-on: self-hosted

    steps:
      - name: cleanup old checkout
        run: sudo chmod +w -R ${GITHUB_WORKSPACE}; sudo rm -rf ${GITHUB_WORKSPACE}/*;

      - name: Change ownership of workspace
        run: sudo chown -R ubuntu:ubuntu ${GITHUB_WORKSPACE}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push to mirror
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.MIRROR_URL }}
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
